# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/example_design/xilinx_pcie_7x_ep_x8g2_VC707.xdc

# IP: ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vc707_pcie_x8_gen2 || ORIG_REF_NAME==vc707_pcie_x8_gen2}]

# XDC: ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2-PCIE_X1Y0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vc707_pcie_x8_gen2 || ORIG_REF_NAME==vc707_pcie_x8_gen2}] {/inst }]/inst ]]
