set_property SRC_FILE_INFO {cfile:/afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc rfile:../../pcie2.0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc id:1 order:EARLY} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2-PCIE_X1Y0.xdc rfile:../../pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2-PCIE_X1Y0.xdc id:2 order:EARLY} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/constrs_1/imports/example_design/xilinx_pcie_7x_ep_x8g2_VC707.xdc rfile:../../pcie2.0.srcs/constrs_1/imports/example_design/xilinx_pcie_7x_ep_x8g2_VC707.xdc id:3} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.runs/synth_1/dont_touch.xdc rfile:dont_touch.xdc id:4} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.000 [get_pins app/PIO/PIO_EP_inst/astro_MEM_inst/clock_gen/inst/clk_in1]
set_property src_info {type:SCOPED_XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name vc707_pcie_x8_gen2_txoutclk_out [get_pins vc707_pcie_x8_gen2_i/inst/pipe_txoutclk_out]
set_property src_info {type:SCOPED_XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins vc707_pcie_x8_gen2_i/inst/inst/pcie_top_i/pcie_7x_i/pcie_block_i/PLPHYLNKUPN]
set_property src_info {type:SCOPED_XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -through [get_pins vc707_pcie_x8_gen2_i/inst/inst/pcie_top_i/pcie_7x_i/pcie_block_i/PLRECEIVEDHOTRST]
set_property src_info {type:XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports emcclk]
set_property src_info {type:XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP37 [get_ports emcclk]
set_property src_info {type:XDC file:3 line:87 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk [get_pins refclk_ibuf/O]
set_property src_info {type:XDC file:3 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -to [get_pins ext_clk.pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/S*]
set_property src_info {type:XDC file:3 line:91 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_125mhz_mux -source [get_pins ext_clk.pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/I0] -divide_by 1 [get_pins ext_clk.pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/O]
set_property src_info {type:XDC file:3 line:93 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_250mhz_mux -source [get_pins ext_clk.pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/I1] -divide_by 1 -add -master_clock clk_250mhz [get_pins ext_clk.pipe_clock_i/pclk_i1_bufgctrl.pclk_i1/O]
set_property src_info {type:XDC file:3 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -name pcieclkmux -physically_exclusive -group clk_125mhz_mux -group clk_250mhz_mux
set_property src_info {type:XDC file:3 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports sys_rst_n]
set_property src_info {type:XDC file:3 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports sys_rst_n]
set_property src_info {type:XDC file:3 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV35 [get_ports sys_rst_n]
set_property src_info {type:XDC file:3 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports led_0]
set_property src_info {type:XDC file:3 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports led_1]
set_property src_info {type:XDC file:3 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports led_2]
set_property src_info {type:XDC file:3 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM39 [get_ports led_0]
set_property src_info {type:XDC file:3 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN39 [get_ports led_1]
set_property src_info {type:XDC file:3 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR37 [get_ports led_2]
set_property src_info {type:XDC file:3 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports led_3]
set_property src_info {type:XDC file:3 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT37 [get_ports led_3]
set_property src_info {type:XDC file:3 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR35 [get_ports GPIO_LED_4_LS]
set_property src_info {type:XDC file:3 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports GPIO_LED_4_LS]
set_property src_info {type:XDC file:3 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP41 [get_ports GPIO_LED_5_LS]
set_property src_info {type:XDC file:3 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports GPIO_LED_5_LS]
set_property src_info {type:XDC file:3 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP42 [get_ports GPIO_LED_6_LS]
set_property src_info {type:XDC file:3 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports GPIO_LED_6_LS]
set_property src_info {type:XDC file:3 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU39 [get_ports GPIO_LED_7_LS]
set_property src_info {type:XDC file:3 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports GPIO_LED_7_LS]
set_property src_info {type:XDC file:3 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB8 [get_ports sys_clk_p]
set_property src_info {type:XDC file:3 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AB7 [get_ports sys_clk_n]
set_property src_info {type:XDC file:3 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports sys_rst_n]
set_property src_info {type:XDC file:3 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property BEL A6LUT [get_cells PIO_EP_insti_9]
set_property src_info {type:XDC file:3 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X29Y9 [get_cells PIO_EP_insti_9]
set_property src_info {type:XDC file:4 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells app/PIO/PIO_EP_inst/astro_MEM_inst/clock_gen]
set_property src_info {type:XDC file:4 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {app/PIO/PIO_EP_inst/astro_MEM_inst/genblk1[0].block_ram}]
set_property src_info {type:XDC file:4 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {app/PIO/PIO_EP_inst/astro_MEM_inst/genblk1[1].block_ram}]
set_property src_info {type:XDC file:4 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {app/PIO/PIO_EP_inst/astro_MEM_inst/genblk1[2].block_ram}]
set_property src_info {type:XDC file:4 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells {app/PIO/PIO_EP_inst/astro_MEM_inst/genblk1[3].block_ram}]
set_property src_info {type:XDC file:4 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells vc707_pcie_x8_gen2_i]
set_property src_info {type:XDC file:4 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells app/PIO/PIO_EP_inst/astro_MEM_inst/clock_gen/inst]
set_property src_info {type:XDC file:4 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells vc707_pcie_x8_gen2_i/inst]
