# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7vx485tffg1761-2

    source $::env(SYNTH_COMMON)/common_vhdl.tcl

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/imports/example_design/window_handler.sv
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/imports/example_design/template_handler.sv
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/imports/example_design/average.sv
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/imports/example_design/user_FPGA_format.sv
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/imports/example_design/address_translator.sv
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/imports/example_design/user_interface.sv
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/imports/example_design/PIO_EP_astroFPGA_MEM.sv
    }
      rt::read_verilog {
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_pipe_clock.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_pipe_eq.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_pipe_drp.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_pipe_rate.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_pipe_reset.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_pipe_sync.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_gtp_pipe_rate.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_gtp_pipe_drp.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_gtp_pipe_reset.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_pipe_user.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_pipe_wrapper.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_qpll_drp.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_qpll_reset.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_qpll_wrapper.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_rxeq_scan.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_pcie_top.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_core_top.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_axi_basic_rx_null_gen.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_axi_basic_rx_pipeline.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_axi_basic_rx.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_axi_basic_top.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_axi_basic_tx_pipeline.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_axi_basic_tx_thrtl_ctl.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_axi_basic_tx.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_pcie_7x.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_pcie_bram_7x.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_pcie_bram_top_7x.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_pcie_brams_7x.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_pcie_pipe_lane.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_pcie_pipe_misc.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_pcie_pipe_pipeline.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_gt_top.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_gt_rx_valid_filter_7x.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2_gt_wrapper.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/source/pcie_7x_v2_1_top.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/vc707_pcie_x8_gen2/synth/vc707_pcie_x8_gen2.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/imports/example_design/PIO_TX_ENGINE.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/imports/example_design/PIO_RX_ENGINE.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/imports/example_design/PIO_TO_CTRL.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/imports/example_design/PIO_EP.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/imports/example_design/PIO.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/imports/example_design/pcie_app_7x.v
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/imports/example_design/xilinx_pcie_2_1_ep_7x.v
    }
      rt::read_vhdl -lib blk_mem_gen_v8_0 {
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_gen_v8_0_synth_comp.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_gen_v8_0_defaults.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_gen_v8_0_pkg.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_gen_getinit_pkg.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_min_area_pkg.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_gen_bindec.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_gen_mux.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_gen_prim_wrapper_v6.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_gen_prim_wrapper_v6_init.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_gen_prim_width.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_gen_generic_cstr.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_gen_ecc_encoder.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_gen_ecc_decoder.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_input_block.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_output_block.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_axi_read_fsm.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_axi_read_wrapper.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_axi_write_fsm.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_axi_write_wrapper.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_axi_regs_fwd.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_gen_top.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_gen_v8_0_synth.vhd
      /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_v8_0/blk_mem_gen_v8_0.vhd
    }
      rt::read_vhdl -lib work /afs/ece.cmu.edu/usr/gcharnma/Private/18-545/RUN3_debugFSM/pcie2.0.srcs/sources_1/ip/blk_mem_gen_0/synth/blk_mem_gen_0.vhd
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-24105-chinook.ece.cmu.edu/realtime/xilinx_pcie_2_1_ep_7x_synth.xdc
    set rt::top xilinx_pcie_2_1_ep_7x
    set rt::flattenHierarchy 1
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter gatedClockConversion 2
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-24105-chinook.ece.cmu.edu/"
    if {$rt::useElabCache == false} {
      rt::run_synthesis -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  return -code "error" $rt::result
}
