# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2.xci
# IP: The module: 'vc707_pcie_x8_gen2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2-PCIE_X1Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vc707_pcie_x8_gen2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]
