# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
create_project -in_memory -part xc7vx485tffg1761-2
set_property board xilinx.com:virtex7:vc707:2.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0

read_ip /afs/ece.cmu.edu/usr/wtabib/astroFPGA/lab3/vc707_pcie_vivado/vc707_pcie_vivado.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2.xci
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/wtabib/astroFPGA/lab3/vc707_pcie_vivado/vc707_pcie_vivado.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/example_design/xilinx_pcie_7x_ep_x8g2_VC707.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/wtabib/astroFPGA/lab3/vc707_pcie_vivado/vc707_pcie_vivado.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2/source/vc707_pcie_x8_gen2-PCIE_X1Y0.xdc]
set_property used_in_implementation false [get_files -all /afs/ece.cmu.edu/usr/wtabib/astroFPGA/lab3/vc707_pcie_vivado/vc707_pcie_vivado.srcs/sources_1/ip/vc707_pcie_x8_gen2/synth/vc707_pcie_x8_gen2_ooc.xdc]
set_property is_locked true [get_files /afs/ece.cmu.edu/usr/wtabib/astroFPGA/lab3/vc707_pcie_vivado/vc707_pcie_vivado.srcs/sources_1/ip/vc707_pcie_x8_gen2/vc707_pcie_x8_gen2.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/ece.cmu.edu/usr/wtabib/astroFPGA/lab3/vc707_pcie_vivado/vc707_pcie_vivado.data/wt [current_project]
set_property parent.project_dir /afs/ece.cmu.edu/usr/wtabib/astroFPGA/lab3/vc707_pcie_vivado [current_project]
synth_design -top vc707_pcie_x8_gen2 -part xc7vx485tffg1761-2
write_checkpoint vc707_pcie_x8_gen2.dcp
report_utilization -file vc707_pcie_x8_gen2_utilization_synth.rpt -pb vc707_pcie_x8_gen2_utilization_synth.pb
